language: node_js
node_js:
  - "8"

stages:
  - install
  - build-website
  - deploy

jobs:
  include:
    - stage: install
      script: npm run install:all
    - stage: build-website
      script: cd ./stemn-frontend-website && npm run build 
    - stage: build-desktop
      script: cd ./stemn-frontend-desktop && npm run build 
    - stage: deploy
      if: branch = master
      script: echo deploy

cache:
  directories:
    - "node_modules"
    - "./stemn-frontend-desktop/node_modules"
    - "./stemn-frontend-website/node_modules"
