language: node_js
node_js:
  - "8"

stages:
  - install
  - build
  - deploy

jobs:
  include:
    - stage: install
      script: npm run install:all
    - stage: build
      script: cd ./stemn-frontend-website && npm run link:shared && npm run build 
    - stage: build
      script: cd ./stemn-frontend-desktop && npm run build 
    - stage: deploy
      if: branch = master
      script: cd ./stemn-frontend-website && npm run deploy:ci

cache:
  directories:
    - "node_modules"
    - "./stemn-frontend-desktop/node_modules"
    - "./stemn-frontend-website/node_modules"
    - "./stemn-frontend-website/build"
